export default Constant = {
  ADD_CONTACTS_SCREEN: "AddContact",
  ADD_ECHO_SCREEN: "AddEcho",
  ADD_FAVORITES_SCREEN: "AddFavorites",
  BLOCKED_SCREEN: "Blocked",
  HOME_SCREEN: "Home",
  INDEX_NAVIGATOR: "Index",
  MANAGER_SCREEN: "Manager",
  NOTIFICATION_SCREEN: "Notification",
  POINTS_SCREEN: "PointsScreen",
  PROFILE_DETAILS_SCREEN: "ProfileDetails",
  PROFILE_NAVIGATOR: "ProfileScreen",
  PROFILE_SCREEN: "Profile",
  SEND_OTP_SCREEN: "SendOtp",
  SEND_THOUGHT_SCREEN: "SendThought",
  SUBSCRIPTION_NAVIGATOR: "SubscriptionNavigator",
  SUBSCRIPTION_SCREEN: "Subscription",
  VERIFY_OTP_SCREEN: "VerifyOtp",
  VIP_ADDECHO_SCREEN: "VipAddEcho",
  VIP_NAVIGATOR: "Vip",
  VIP_SEARCH_SCREEN: "VipSearch",
  VIP_SENDTHOUGHT_SCREEN: "VipSendThought",
};
