export default DataConstants = {
  ADSSTATS: "adsStats",
  BLOCKED: "blocked",
  CONTACTS_UPDATE: "contactsUpdate",
  CONTACTS: "userContacts",
  DETAILS: "userDetails",
  ECHO_MESSAGE_UPDATE: "echoMessagesUpdate",
  ECHO_MESSAGE: "userEchoMessage",
  ECHO_WHEN: "userEchoWhen",
  EXPIRED_UPDATE: "expiredUpdate",
  FAVORITES_UPDATE: "favoritesUpdate",
  FAVORITES: "userFavorites",
  LOCAL_SAVED_THOUGHTS: "localSavedThoughts",
  MESSAGES_UPDATE: "messagesUpdate",
  MESSAGES: "userMessages",
  NOTIFICATIONS_UPDATE: "notificationUpdate",
  NOTIFICATIONS: "userNotifications",
  PHONE_CONTACTS_UPDATE: "phoneContactsUpdate",
  PHONE_CONTACTS: "userPhoneContacts",
  POINTS: "userPoints",
  SEARCH_HISTORY: "userSearchHistory",
  STATS: "stats",
  THOUGHTS: "userThoughts",
  VIP: "vip",
};
